"""

Handles:
    - Converting the raw .sav file to CSV (run once)
    - Loading the cleaned CSV
    - Replacing negative codes (-1 Refused, -2 Not asked) with NaN
    - Providing value labels for all coded variables

Usage:
    from src.data_loader import load_data, label_column

    df, labels = load_data()  # Returns cleaned DataFrame + value label dict

Run standalone to convert .sav → .csv:
    python src/data_loader.py --convert
"""

import os
import sys
import json
import warnings
import numpy as np
import pandas as pd
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

SAV_FILE = DATA_RAW / "HCMST 2017 to 2022 small public version 2.2.sav"
CSV_FILE = DATA_PROCESSED / "hcmst_clean.csv"
LABELS_FILE = DATA_PROCESSED / "value_labels.json"


# ---------------------------------------------------------------------------
# Value labels — loaded from the JSON file generated by --convert.
# This contains ALL 586 variable mappings extracted from the SPSS metadata,
# so every coded variable in the dataset can be translated to readable labels.
# ---------------------------------------------------------------------------


def _load_value_labels():
    """Load value labels from the JSON file. Returns dict with numeric keys."""
    if not LABELS_FILE.exists():
        warnings.warn(
            f"Value labels file not found at {LABELS_FILE}.\n"
            f"Run `python src/data_loader.py --convert` first.\n"
            f"Returning empty labels dict."
        )
        return {}

    with open(LABELS_FILE, "r") as f:
        raw = json.load(f)

    # Convert string keys back to numeric (e.g., "1.0" → 1.0)
    labels = {}
    for var_name, mapping in raw.items():
        numeric_mapping = {}
        for k, v in mapping.items():
            try:
                num_key = float(k)
                # Use int if it's a whole number (e.g., 1.0 → 1)
                if num_key == int(num_key):
                    num_key = int(num_key)
                numeric_mapping[num_key] = v
            except ValueError:
                numeric_mapping[k] = v
        labels[var_name] = numeric_mapping

    return labels


VALUE_LABELS = _load_value_labels()

# Negative codes that should be treated as NaN
NEGATIVE_CODES = {-1: "Refused", -2: "Not asked"}


# ---------------------------------------------------------------------------
# Core loading functions
# ---------------------------------------------------------------------------


def convert_sav_to_csv():
    """Convert the raw .sav file to a clean CSV. Run once."""
    try:
        import pyreadstat
    except ImportError:
        print("ERROR: pyreadstat is required to read .sav files.")
        print("Install it with: pip install pyreadstat")
        sys.exit(1)

    print(f"Reading {SAV_FILE} ...")
    df, meta = pyreadstat.read_sav(str(SAV_FILE))

    print(f"  Shape: {df.shape}")
    print(f"  Saving to {CSV_FILE} ...")

    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    df.to_csv(CSV_FILE, index=False)

    # Save value labels from SPSS metadata
    spss_labels = {}
    for var, mapping in meta.variable_value_labels.items():
        spss_labels[var] = {str(k): v for k, v in mapping.items()}

    with open(LABELS_FILE, "w") as f:
        json.dump(spss_labels, f, indent=2)

    print(f"  Saved value labels to {LABELS_FILE}")
    print("Done! You can now use load_data() to load the clean CSV.")


def load_raw():
    """Load the CSV. Returns raw DataFrame."""
    if not CSV_FILE.exists():
        raise FileNotFoundError(
            f"Clean CSV not found at {CSV_FILE}.\n"
            f"Run `python src/data_loader.py --convert` first to convert the .sav file."
        )
    return pd.read_csv(CSV_FILE)


def load_data(
    replace_negatives=True, drop_high_missing_cols=False, missing_threshold=0.95
):
    """
    Load and clean the HCMST dataset.

    Parameters
    ----------
    replace_negatives : bool
        If True, replace -1 (Refused) and -2 (Not asked) with NaN.
    drop_high_missing_cols : bool
        If True, drop columns where missing % exceeds `missing_threshold`.
    missing_threshold : float
        Threshold for dropping columns (default 0.95 = 95% missing).

    Returns
    -------
    df : pd.DataFrame
        Cleaned DataFrame.
    labels : dict
        Value label mappings for key variables.
    """
    df = load_raw()

    if replace_negatives:
        df = _replace_negative_codes(df)

    if drop_high_missing_cols:
        before = df.shape[1]
        mask = df.isnull().mean() < missing_threshold
        df = df.loc[:, mask]
        print(
            f"Dropped {before - df.shape[1]} columns with >{missing_threshold*100:.0f}% missing"
        )

    return df, VALUE_LABELS


def _replace_negative_codes(df):
    """Replace -1 (Refused) and -2 (Not asked) with NaN across all numeric columns."""
    df = df.copy()
    numeric_cols = df.select_dtypes(include=[np.number]).columns

    # Only replace -1 and -2 in columns where they represent refusal/not-asked,
    # NOT in columns where negative values are meaningful (e.g., log income, changes)
    safe_negative_cols = [
        col
        for col in numeric_cols
        if not any(
            x in col.lower()
            for x in ["log", "change", "diff", "duration", "time_from", "year_met"]
        )
    ]

    for col in safe_negative_cols:
        df[col] = df[col].replace({-1: np.nan, -2: np.nan})

    return df


def label_column(series, var_name):
    """
    Map numeric codes to labels for a given variable.

    Usage:
        df['gender_label'] = label_column(df['w1_ppgender'], 'w1_ppgender')
    """
    if var_name in VALUE_LABELS:
        mapping = VALUE_LABELS[var_name]
        # Build a mapping that works with both int and float keys
        # (pandas columns are often float64, but our dict keys may be int)
        flexible_mapping = {}
        for k, v in mapping.items():
            flexible_mapping[k] = v
            if isinstance(k, int):
                flexible_mapping[float(k)] = v
        return series.map(flexible_mapping)
    else:
        warnings.warn(f"No value labels found for '{var_name}'")
        return series


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if "--convert" in sys.argv:
        convert_sav_to_csv()
    else:
        print("Usage:")
        print(
            "  python src/data_loader.py --convert   # Convert .sav to .csv (run once)"
        )
        print()
        print("In your notebooks:")
        print("  from src.data_loader import load_data")
        print("  df, labels = load_data()")
